"""
report_generator.py
===================
Module for generating a professional PDF diagnostic report for ColonAI.
Uses fpdf2 for document construction.
"""

import os
from datetime import datetime
import io
import numpy as np
from PIL import Image
from fpdf import FPDF

class ColonAI_Report(FPDF):
    def header(self):
        # Logo or Title Header
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(41, 128, 185)  # Professional Blue
        self.cell(0, 15, "ColonAI Diagnostic Report", ln=True, align="C")
        
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Automated Histopathology Analysis System", ln=True, align="C")
        
        self.ln(5)
        self.set_draw_color(41, 128, 185)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-25)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        
        # Disclaimer
        disclaimer = (
            "DISCLAIMER: This report is generated by an experimental AI model (CLAM MIL) for research and demonstration purposes only. "
            "It is NOT a substitute for expert pathological diagnosis by a certified medical professional."
        )
        self.multi_cell(0, 4, disclaimer, align="C")
        
        self.ln(2)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()} / {{nb}}", align="C")

def generate_pdf_report(result, slide_name):
    """
    Generate a PDF report from inference results.
    
    Parameters
    ----------
    result : dict
        Output from pipeline.run_full_inference
    slide_name : str
        Original filename of the slide
        
    Returns
    -------
    bytes
        PDF file content as bytes
    """
    pdf = ColonAI_Report()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # --- Section: Case Information ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Case Information", ln=True)
    
    pdf.set_font("Helvetica", "", 11)
    # Parse Case ID from filename if possible (TCGA convention)
    case_id = slide_name.split(".")[0]
    
    data = [
        ["Slide ID:", slide_name],
        ["Analysis Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Total Patches:", f"{result['n_patches']:,}"],
        ["Model Architecture:", "CLAM-SB (Ensemble)"],
    ]
    
    col_width = [40, 150]
    for row in data:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(col_width[0], 7, row[0])
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(col_width[1], 7, row[1], ln=True)
    
    pdf.ln(10)
    
    # --- Section: Diagnostic Findings ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Diagnostic Findings", ln=True)
    
    # Styling for result
    is_tumor = result["prediction"] == 1
    result_text = "TUMOR DETECTED" if is_tumor else "NORMAL TISSUE (No Tumor Detected)"
    result_color = (192, 57, 43) if is_tumor else (39, 174, 96) # Red or Green
    
    pdf.set_fill_color(*result_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"  {result_text}", ln=True, fill=True)
    
    pdf.ln(2)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    
    prob = result["probability"]
    pdf.cell(0, 8, f"Tumor Probability: {prob:.4f} ({prob*100:.1f}%)", ln=True)
    pdf.cell(0, 8, f"Decision Threshold: 0.2760", ln=True)
    pdf.cell(0, 8, f"Confidence Score: {result['confidence']:.4f}", ln=True)
    
    pdf.ln(10)
    
    # --- Section: Visual Analysis ---
    if result["has_coords"] and result.get("heatmap_grid") is not None:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Spatial Attention Visualization (Coarse Grid)", ln=True)
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 5, "Hotspots (red) indicate regions with high diagnostic significance.", ln=True)
        pdf.ln(5)
        
        # Convert numpy heatmap to PIL Image for embedding
        # We need to render the heatmap like plot_heatmap does, but into a buffer
        import matplotlib.pyplot as plt
        
        fig, ax = plt.subplots(figsize=(6, 5))
        im = ax.imshow(
            result["heatmap_grid"],
            cmap="jet",
            interpolation="nearest",
            origin="lower",
            vmin=0.0,
            vmax=1.0,
        )
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04).set_label("Normalised Attention")
        ax.set_title(f"Focus Map: {slide_name}")
        ax.set_xlabel("Grid column")
        ax.set_ylabel("Grid row")
        
        img_buf = io.BytesIO()
        plt.savefig(img_buf, format='png', dpi=150, bbox_inches="tight")
        img_buf.seek(0)
        plt.close(fig)
        
        # Embed image in PDF
        # Center horizontally
        x_pos = (210 - 120) / 2 # A4 width is 210mm
        pdf.image(img_buf, x=x_pos, y=pdf.get_y(), w=120)
        pdf.ln(90) # Adjust line height for image
        
    pdf.ln(5)
    # --- Final notes ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Technical Note", ln=True)
    pdf.set_font("Helvetica", "", 10)
    note = (
        "This analysis used an ensemble of 5-fold cross-validated models trained on the TCGA-COAD/READ datasets. "
        "The heatmaps are reconstructed using patch-level coordinates and normalized attention scores."
    )
    pdf.multi_cell(0, 5, note)
    
    # Return as bytes
    return pdf.output() # In fpdf2, .output() returns a bytearray if no name is given (default) or use dest='S'
